2019.6
## 八：异常处理
- 把有风险的代码块包含在`try/catch`块中。  
- 异常是一种Exception类型的对象。Catch住的也是对象。  
- 这个对象可以调用方法。`PrintStackTrace()` 列出有用的信息。  
- 如果有抛出异常，必须声明他会抛出什么异常 方法名后面加 throws xxxException  
- RuntimeException被称为不检查异常，我可以自己抛出与抓住他们，但是没有必要，编译器不管的。  
- 除了RuntimException之外，编译器会关照Exception的所有子类 编译器不管运行时异常。  
- 因为大部分的RuntimeException都是因为程序逻辑问题。  
- Try/catch 是用来处理真正的异常，而不是逻辑错误。Try/catch块要做的是恢复的尝试，或者至少优雅的列出错误信息。  
- 方法可以用throw抛出异常兑现。  
- 	`Throw new Exception；`
- 异常处理/恢复程序块放在catch中。
- Finally块是用来存放不管有没有异常都得执行的程序。
    - 	如果try/catch块中有return指令，还是会执行finally流程会调到finally然后再回到return。
- 可以处理多重异常，throws 多个Exception。有多个catch语句 不同的Exception子类对象。
- 异常也是多态的，
    - throws 父类，便可以抛出其所有子类而不用个别的声明。
    - Catch父类，可以抛出其所有的子类异常。
- 最好为需要单独处理的异常编写不同的catch块。
- Catch Exception 会捕获所有异常，所以不知道哪里出错。有多个catch时要从小排到大。
- DUCK：
- 可以不写trycatch语句，但是throws异常，这样谁调用这个方法，谁就自己处理异常，我不管了。
- 异常处理规格：
    - Catch与finally不能没有try
    - Try与catch之间不能有程序
    - Try一定要有catch或finally
    - 只有finally没有catch的try必须要声明异常 throws
